import type { Notify } from '../types/domain'
import { PageHeader } from '../components/common/PageHeader'
import { useAssets } from '../features/assets/useAssets'

const gradients = ['gallery-a','gallery-b','gallery-c','gallery-d','gallery-e','gallery-f','gallery-g','gallery-h','gallery-i','gallery-j','gallery-k','gallery-l','gallery-m','gallery-n','gallery-o']
const placeholders = ['晨雾里的小屋','胶片人像','山间少年','猫咪日记','夏日白衬衫','湖边散步']

export function AssetsPage({ notify }: { notify: Notify }) {
  const library = useAssets()
  const displayAssets = library.visibleAssets
  const usageMb = Math.round((library.assets.reduce((sum, asset) => sum + asset.sizeBytes, 0) / 1024 / 1024) * 10) / 10
  return <div className="library-page"><PageHeader eyebrow="本地资产" title="图库" actions={<button className="light-button" onClick={() => { void library.refresh(); notify('图库已刷新') }}>↻ 刷新</button>} /><div className="library-stats"><div className="search-box">⌕<input value={library.query} onChange={event => library.setQuery(event.target.value)} placeholder="搜索 ID、类型或哈希" /></div><div className="stats"><span>▧ 图片总数 <strong>{library.assets.length || 0}</strong></span><span>▤ 占用空间 <strong>{usageMb} MB</strong></span></div></div><div className="filter-row">{(['全部','最近生成','收藏'] as const).map(item => <button key={item} className={library.filter === item ? 'selected' : ''} onClick={() => { library.setFilter(item); notify(`已切换${item}`) }}>{item}</button>)}</div>{library.loading ? <div className="history-placeholder"><span>◌</span><h2>正在加载素材</h2><p>从本地资产仓库读取缩略图。</p></div> : displayAssets.length === 0 ? <div className="gallery-grid">{placeholders.map((name, index) => <button className="gallery-card" key={name} onClick={() => notify(`示例资产「${name}」`)}><div className={`gallery-image ${gradients[index]}`}><span>✦</span></div><div className="gallery-meta"><strong>{name}</strong><span>示例占位资产</span><small>尚未生成本地文件</small></div></button>)}</div> : <div className="gallery-grid">{displayAssets.map((asset, index) => <div className="gallery-card asset-card" key={asset.id}><button onClick={() => notify(`已打开资产「${asset.id.slice(0, 12)}」`)}><div className={`gallery-image ${gradients[index % gradients.length]}`}><span>{asset.kind === 'video' ? '▶' : asset.kind === 'audio' ? '◖' : '✦'}</span></div><div className="gallery-meta"><strong>{asset.kind === 'video' ? '视频资产' : asset.kind === 'audio' ? '音频资产' : '图片资产'}</strong><span>{asset.id.slice(0, 16)}</span><small>{asset.mimeType} · {Math.round(asset.sizeBytes / 1024)} KB</small></div></button><button className="asset-delete" onClick={() => { void library.remove(asset.id); notify('资产已删除') }}>删除</button></div>)}</div>}</div>
}
