import { useRef } from 'react'
import type { Notify } from '../types/domain'
import { useAudioWorkspace } from '../features/audio/useAudioWorkspace'

export function AudioPage({ notify }: { notify: Notify }) {
  const audio = useAudioWorkspace(notify)
  const fileInput = useRef<HTMLInputElement>(null)
  const isTts = audio.tab === 'tts'
  return <div className="creative-page voice-page"><div className="creative-header"><div><span className="eyebrow">声音工作室</span><h1>{isTts ? '语音合成' : '语音识别'}</h1></div><div className="creative-tabs"><button className={isTts ? 'selected' : ''} onClick={() => audio.setTab('tts')}>语音合成</button><button className={!isTts ? 'selected' : ''} onClick={() => audio.setTab('stt')}>语音识别</button></div></div><div className="voice-card"><textarea className="unified-input" rows={8} value={isTts ? audio.text : ''} onChange={event => audio.setText(event.target.value)} placeholder={isTts ? '输入需要合成的文本…' : '选择音频或视频文件，生成文本…'} readOnly={!isTts}/>{!isTts && <div className="audio-file-picker"><input ref={fileInput} type="file" accept="audio/*,video/*" hidden onChange={event => audio.chooseFile(event.target.files?.[0])}/><button className="light-button" onClick={() => fileInput.current?.click()}>选择音频 / 视频</button><span>{audio.sourceFile?.name ?? '未选择文件'}</span></div>}<div className="voice-fields">{isTts ? <select value={audio.voice} onChange={event => audio.setVoice(event.target.value)}><option>Aria · 温暖女声</option><option>River · 平静男声</option></select> : <select value={audio.language} onChange={event => audio.setLanguage(event.target.value)}><option>中文（普通话）</option><option>English</option></select>}<select value={audio.format} onChange={event => audio.setFormat(event.target.value)}>{(isTts ? ['MP3', 'WAV'] : ['TXT', 'JSON', 'SRT', 'VTT']).map(item => <option key={item}>{item}</option>)}</select><button onClick={() => notify(isTts ? '试听已准备' : '识别预览已准备')} disabled={audio.status === 'running'}>▶ 试听</button><button className="dark-action" onClick={() => { void audio.submit() }} disabled={audio.status === 'running'}>{audio.status === 'running' ? `${audio.progress}%` : isTts ? '合成语音 →' : '开始识别 →'}</button></div>{audio.status === 'succeeded' && <div className="audio-result">{isTts ? '音频已生成，可播放或下载。' : '识别文本已生成，可导出字幕。'}</div>}</div></div>
}
