import { useMemo, useState } from 'react'
import type { Notify } from '../types/domain'
import { useGatewayProfiles } from '../features/gateways/useGatewayProfiles'

export function ChannelPage({ notify }: { notify: Notify }) {
  const gateways = useGatewayProfiles()
  const [query, setQuery] = useState('')
  const profiles = useMemo(() => gateways.profiles.filter(profile => profile.id !== 'mock-default' && !profile.baseUrl.startsWith('mock://') && (!query.trim() || `${profile.id} ${profile.name} ${profile.baseUrl} ${profile.protocol}`.toLowerCase().includes(query.trim().toLowerCase()))), [gateways.profiles, query])
  return <div className="channel-page"><div className="channel-heading"><div><span className="channel-kicker">管理中心</span><h1>渠道</h1></div><div className="channel-actions"><button onClick={() => notify('批量操作已打开')}>☷ 批量操作</button><button onClick={() => notify('排序已切换')}>↕ 使用 ID 排序</button><button className="channel-primary" onClick={() => { gateways.addProfile(); notify('已创建新的渠道草稿') }}>＋ 创建渠道</button></div></div><div className="channel-filters"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="按名称、ID、地址或协议筛选…" /><button onClick={() => notify('状态筛选已打开')}>⊕ 状态</button><button onClick={() => notify('分组筛选已打开')}>⊕ 分组</button></div>{profiles.length === 0 ? <div className="channel-empty"><strong>暂无渠道</strong><span>在设置中新增网关并配置 API Key 后，渠道会显示在这里。</span></div> : <div className="channel-table"><div className="channel-table-head"><span>ID</span><span>名称</span><span>类型</span><span>状态</span><span>地址</span><span>默认</span><span>操作</span></div>{profiles.map(profile => <button className="channel-row" key={profile.id} onClick={() => notify(`已打开渠道「${profile.name}」`)}><span>{profile.id}</span><span className="channel-name"><strong>{profile.name}</strong></span><span className="channel-type">{profile.protocol}</span><span className={profile.enabled ? 'channel-enabled' : 'channel-disabled'}>{profile.enabled ? '已启用' : '已禁用'}</span><span>{profile.baseUrl}</span><span className="channel-pill">{profile.isDefault ? '是' : '否'}</span><span className="channel-tools">···</span></button>)}</div>}</div>
}
