import { useState } from 'react'
import type { Notify } from '../types/domain'
import { useChatWorkspace } from '../features/chat/useChatWorkspace'

export function ChatPage({ notify }: { notify: Notify }) {
  const workspace = useChatWorkspace()
  const [prompt, setPrompt] = useState('')
  const send = () => { if (!prompt.trim()) return notify('请输入消息'); void workspace.send(prompt); setPrompt(''); notify('消息已发送') }
  const messages = workspace.activeSession?.messages ?? []
  return <div className="creative-page chat-page"><div className="creative-header"><div><span className="eyebrow">聊天工作区</span><h1>聊天</h1></div><div className="creative-tabs"><button onClick={workspace.createSession}>＋ 新会话</button></div></div><div className="chat-workspace"><aside className="chat-sessions"><div className="chat-sessions-title">会话历史</div>{workspace.sessions.map(session => <button key={session.id} className={session.id === workspace.activeSessionId ? 'selected' : ''} onClick={() => workspace.setActiveSessionId(session.id)}><strong>{session.title}</strong><small>{session.messages.length} 条消息</small></button>)}{workspace.activeSession && <button className="chat-delete" onClick={() => workspace.deleteSession(workspace.activeSession.id)}>删除当前会话</button>}</aside><section className="chat-thread"><div className="chat-thread-toolbar"><select value={workspace.activeSession?.modelId ?? 'gpt-4.1'} onChange={event => workspace.setModel(event.target.value)}>{workspace.models.map(model => <option key={model}>{model}</option>)}</select>{workspace.isStreaming && <button onClick={() => { workspace.stop(); notify('已停止生成') }}>停止</button>}</div><div className="chat-messages">{messages.length === 0 ? <div className="chat-canvas"><div className="empty-orb">✦</div><h2>今天想做什么？</h2><p>用一句话开始一段新的创作。</p></div> : messages.map(message => <article className={`chat-message ${message.role}`} key={message.id}><div className="chat-message-role">{message.role === 'user' ? '你' : 'Lingjing'}</div><div className="chat-message-content">{message.content || (message.status === 'streaming' ? '生成中…' : '')}</div></article>)}</div><div className="chat-composer"><textarea className="unified-input" autoFocus value={prompt} onChange={event => setPrompt(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); send() } }} placeholder="输入消息，描述你的想法…" rows={4}/><div className="composer-footer"><div className="composer-controls"><button onClick={() => notify('附件选择器已打开')}>＋</button><button onClick={() => notify('已开启深度思考')}>✧ 深度思考</button></div><button className="send-button" onClick={send} disabled={workspace.isStreaming}>↑</button></div></div></section></div></div>
}
