import type { Notify } from '../types/domain'
import { useVideoWorkspace } from '../features/video/useVideoWorkspace'

export function VideoPage({ notify }: { notify: Notify }) {
  const video = useVideoWorkspace(notify)
  const capabilities = video.capabilities
  const operations = capabilities?.operations ?? ['generate', 'edit', 'extend']
  return <div className="creative-page studio-page video-studio-page"><div className="creative-header"><div><span className="eyebrow">视频工作区</span><h1>视频</h1></div></div><div className="notice-bar"><span>✧</span><span>参数会根据当前模型能力自动调整。</span><button onClick={() => notify('视频能力说明已打开')}>查看说明 ↗</button></div><div className="canvas video-canvas"><div className="canvas-center"><span className="canvas-icon">▣</span><strong>{video.status === 'running' ? `生成中 ${video.progress}%` : video.status === 'succeeded' ? '视频任务已完成' : video.status === 'canceled' ? '视频任务已取消' : '描述你的想法，生成一段视频'}</strong><span>{video.status === 'succeeded' ? '结果已写入视频库和素材库' : video.capabilitiesLoading ? '正在读取模型能力…' : '视频默认只显示封面，不自动播放'}</span></div></div><div className="prompt-dock video-dock"><div className="operation-tabs">{operations.map(item => <button key={item} className={video.operation === item ? 'selected' : ''} onClick={() => video.setOperation(item)}>{item === 'generate' ? '生成' : item === 'edit' ? '编辑' : '延长'}</button>)}</div><textarea className="unified-input" value={video.prompt} onChange={event => video.setPrompt(event.target.value)} placeholder="描述视频画面、动作、镜头和节奏。" rows={3}/><div className="dock-controls"><select value={video.model} onChange={event => { void video.selectModel(event.target.value) }}><option>grok-imagine-video</option><option>veo-3</option><option>sora-2</option></select><button onClick={video.selectFirstFrame}>▧ 首帧图</button><button onClick={() => { video.setSourceVideoAssetId('asset-source-demo'); notify('已选择示例源视频') }}>▧ 源视频</button><button onClick={video.selectReferenceImage}>▧ 参考图</button>{(capabilities?.maxReferenceVoices ?? 0) > 0 && <button onClick={video.toggleReferenceVoice}>◖ {video.referenceVoiceIds.length ? '已使用参考音色' : '参考音色'}</button>}<select value={video.durationSec} onChange={event => video.setDurationSec(Number(event.target.value))}>{(capabilities?.durations ?? [6, 12, 18]).map(value => <option key={value} value={value}>{value} 秒</option>)}</select><select value={video.aspectRatio} onChange={event => video.setAspectRatio(event.target.value)}>{(capabilities?.aspectRatios ?? ['16:9']).map(value => <option key={value}>{value}</option>)}</select><select value={video.resolution} onChange={event => video.setResolution(event.target.value)}>{(capabilities?.resolutions ?? ['720p']).map(value => <option key={value}>{value}</option>)}</select>{video.status === 'running' ? <button className="dock-submit" onClick={video.cancel}>■</button> : video.status === 'failed' || video.status === 'canceled' ? <button className="dock-submit" onClick={() => { void video.retry() }}>↻</button> : <button className="dock-submit" onClick={() => { void video.start() }} disabled={video.capabilitiesLoading}>↑</button>}</div></div></div>
}
export default VideoPage
